### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by zeyonaut** [LaurentTreguier/autocomplete-dcd#3]
**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.2
**Thrown From**: [autocomplete-dcd](https://github.com/LaurentTreguier/autocomplete-dcd) package, v1.6.1
### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:298

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at Object.module.exports.getDubImports (/Users/Home/.atom/packages/autocomplete-dcd/lib/dcd-provider.coffee:49:24)
    at Object.module.exports.startServer (/Users/Home/.atom/packages/autocomplete-dcd/lib/dcd-provider.coffee:35:6)
    at ChildProcess.<anonymous> (/Users/Home/.atom/packages/autocomplete-dcd/lib/dcd-provider.coffee:169:10)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".DS_Store"
    ],
    "themes": [
      "isotope-light-ui",
      "octocat-syntax"
    ]
  },
  "autocomplete-dcd": {
    "dcdClient": "/usr/local/bin/dcd-client",
    "dcdServer": "/usr/local/bin/dcd-server"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-dcd, v1.6.1
flow, v0.5.3
haxe, v0.8.10
isotope-light-ui, v2.2.6
language-cpp14, v0.5.0
language-d, v3.2.3
language-haxe, v0.4.0
language-lua, v0.9.4
linter, v1.11.3
minimap, v4.19.0
octocat-syntax, v0.1.5

# Dev
No dev packages
```

**Comment by LaurentTreguier** [comment]
This is going to be hard to debug since I don't have Mac OS X... From what I looked up this exception seems to be throw  because of permission problem. How is dub installed on your system ? Do you have the permisson to execute it ?

**Comment by zeyonaut** [comment]
Dub was installed through Homebrew, and I can execute it through terminal with no sudo required on my current user.

**Comment by LaurentTreguier** [comment]
It's weird... the EACCES error seems to always be thrown because of a permission problem.
Has the extension ever worked before, or is this the first time you tried ?
I've seen someone have such a problem after an upgrade of OS X too... Have you done one recently ?
If you can use dub then you should have no problem using it through Atom. If the permissions work in OS X the same way as they do in linux then Atom has the same rights you have.
What are the exact permissions and owner of the dub executable ? My dub executable is :
`-rwxr-xr-x 1 root root 5.9M Sep 21 18:05 /bin/dub`
I am already sure yours are like this too, but for now I can't seem to see what's wrong...

**Comment by zeyonaut** [comment]
`lrwxr-xr-x  1 Home  admin  28 Mar 17 11:59 dub -> ../Cellar/dub/0.9.24/bin/dub`

Perhaps you know something about these permissions that I don't?

**Comment by LaurentTreguier** [comment]
No, all I can make of this is that it's perfectly normal... There are some people I know who are more familiar than me with OS X. I will see if they may have any idea of what could be going on.

**Comment by LaurentTreguier** [comment]
Actually, are you launching Atom from the terminal ? If not, could you try that ? I just realized this could be the same sort of problem as #1

**Comment by zeyonaut** [comment]
Sorry for the late response. Yes, it can be launched from the terminal, nice one!

**Comment by LaurentTreguier** [comment]
There is a package I linked in the other issue that is supposed to solve this issue if one uses it in a package. I'll see if I can try and do it so that it works without having to launch Atol from the terminal
